# Azure DevOps Pipeline for MAUI Android Only (.NET 9)
trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '9.0.x'
  targetFramework: 'net9.0-android'
  androidRuntime: 'android-arm64'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)
    
- script: dotnet workload install android maui-android
  displayName: 'Install Android and MAUI Android Workloads'
  
- task: DotNetCoreCLI@2
  displayName: 'Restore Android Packages Only'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    arguments: '-f $(targetFramework) --runtime $(androidRuntime)'
    
- task: DotNetCoreCLI@2
  displayName: 'Build Android App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-f $(targetFramework) -c $(buildConfiguration) --runtime $(androidRuntime) --no-restore'
    
- task: DotNetCoreCLI@2
  displayName: 'Publish Android APK'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '-f $(targetFramework) -c $(buildConfiguration) --runtime $(androidRuntime) --no-restore --no-build -p:AndroidPackageFormat=apk'
    publishWebProjects: false
    zipAfterPublish: false
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Android APK Artifact'
  inputs:
    pathToPublish: 'bin/$(buildConfiguration)/$(targetFramework)/$(androidRuntime)/publish'
    artifactName: 'maui-efcore-pipeline-build'